version: '3'
services:
  financial-planning-app:
    image: guillermomaschwitz/${PROJECT_NAME}:${PROJECT_VERSION}-development
    container_name: ${PROJECT_NAME}
    volumes:
      - ./${PROJECT_NAME}:/home/node/app
    networks:
      net: {}
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
      - 9005:9005
    env_file:
    - .env
    - .secrets
    command: sh -c "ng serve"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.4.0.0/16